---
- name: Playbook for Keycloak Hosts
  hosts: keycloak
  vars:
    keycloak_admin_password: "remembertochangeme"
    sso_enable: True
  roles:
    - middleware_automation.redhat_csp_download.redhat_csp_download
    - middleware_automation.keycloak.keycloak